name: assistech
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'  # Cambiado a 3.0.6 para que sea compatible con Dart SDK 3.0.6

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^7.6.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  geoflutterfire: ^2.2.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  qr_code_scanner: ^0.4.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  qr_flutter: ^3.0.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  mysql1: ^0.19.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  sqflite: ^1.3.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  http: ^0.13.3
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.14
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6
  flutter_launcher_icons: ^0.8.1  # Ajustado a una versión anterior que sea compatible con Dart SDK 3.0.6

flutter_icons:
  android: true
  ios: true
  image_path: "assest/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assest/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
